# @package _global_
defaults:
  - override /model: demucs
  - override /effects: all
seed: 12345
sample_rate: 44100
chunk_size: 242550 # 5.5s
logs_dir: "./lightning_logs"

accelerator: "gpu"
log_audio: True
# Effects
num_kept_effects: [0, 0] # [min, max]
num_removed_effects: [0, 5] # [min, max]
shuffle_kept_effects: False
shuffle_removed_effects: False
num_classes: 5
effects_to_keep:
effects_to_remove:
  - reverb
  - delay
  - chorus
  - distortion
  - compressor
datamodule:
  train_batch_size: 1
  test_batch_size: 1
  num_workers: 8
  train_dataset: None
  val_dataset: None
  test_dataset:
    _target_: remfx.datasets.InferenceDataset
    root: ${oc.env:DATASET_ROOT}
    sample_rate: ${sample_rate}

ckpts:
  RandomPedalboardDistortion:
    model: ${model}
    ckpt_path: "ckpts/demucs_distortion_aug.ckpt"
  RandomPedalboardCompressor:
    model: ${model}
    ckpt_path: "ckpts/demucs_compressor_aug.ckpt"
  RandomPedalboardReverb:
    model: ${model}
    ckpt_path: "ckpts/demucs_reverb_aug.ckpt"
  RandomPedalboardChorus:
    model: ${model}
    ckpt_path: "ckpts/demucs_chorus_aug.ckpt"
  RandomPedalboardDelay:
    model: ${model}
    ckpt_path: "ckpts/demucs_delay_aug.ckpt"
inference_effects_ordering:
  - "RandomPedalboardCompressor"
  - "RandomPedalboardDistortion"
  - "RandomPedalboardChorus"
  - "RandomPedalboardDelay"
  - "RandomPedalboardReverb"
num_bins: 1025
inference_effects_shuffle: False
inference_use_all_effect_models: False
